name: worksched_dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # dashboard samplepng
    - assets/res/dashboard.png

    # bottomnav
    - assets/bottomnav/timelog32x32.png
    - assets/bottomnav/change_shift32x32.png
    - assets/bottomnav/change_day_type32x32.png
    - assets/bottomnav/official_business32x32.png
    - assets/bottomnav/leaves32x32.png
    - assets/bottomnav/reimburstment32x32.png
    - assets/bottomnav/overtime32x32.png
    - assets/bottomnav/work_from_home32x32.png
    - assets/bottomnav/undertime32x32.png
    - assets/bottomnav/my_request32x32.png

    # leftnav
    - assets/leftnav/dashboard18x18.png
    - assets/leftnav/time_sheet18x18.png
    - assets/leftnav/daily_time_record18x18.png
    - assets/leftnav/leave_ledger18x18.png
    - assets/leftnav/loan_ledger18x18.png
    - assets/leftnav/performance_evaluation18x18.png
    - assets/leftnav/on_boarding18x18.png
    - assets/leftnav/faqs18x18.png
    - assets/leftnav/accountability_scanner18x18.png
    - assets/leftnav/reports18x18.png

    # midnav
    # - assets/midnav/bundy32x32.png
    # - assets/midnav/balances32x32.png
    # - assets/midnav/announcements32x32.png
    # - assets/midnav/survey32x32.png

    # topnav
    # - assets/topnav/analytics32x32.png
    # - assets/topnav/calendar32x32.png
    # - assets/topnav/my_team32x32.png
